{{- if .Values.ingressroute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ .Release.Name }}-ssh
  namespace: {{ .Release.Name }}
spec:
  entryPoints:
    - ssh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ .Release.Name }}-ssh
          port: 22
{{- end }}
