clusterIssuer:
  name: letsencrypt-staging
  email: "notarealemail@gmail.com"
  server: "https://acme-staging-v02.api.letsencrypt.org/directory"
  privateKeySecretRef:
    name: letsencrypt-staging
  solvers:
    cloudflare:
      apiTokenSecretRef:
        name: cert-manager-cloudflare-api-credentials
        key: apiKey
