apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.email | quote }}
    server: {{ .Values.clusterIssuer.server | quote }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretRef.name | quote }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.clusterIssuer.solvers.cloudflare.apiTokenSecretRef.name | quote }}
              key: {{ .Values.clusterIssuer.solvers.cloudflare.apiTokenSecretRef.key | quote }}
