longhorn:
  persistence:
    defaultClass: true
    defaultFsType: ext4
    reclaimPolicy: Retain
    defaultNodeSelector:
      enable: true
      selector: "longhorn-true"

  defaultSettings:
    createDefaultDiskLabeledNodes: true

  ingress:
    enabled: false

ingressroute:
  enabled: true
  host: "longhorn.example.com"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    secretName: "longhorn-tls"
certificate:
  enabled: true
  name: longhorn-tls
  secretName: longhorn-tls
  issuer:
    name: "letsencrypt-prod"  # This value can be set via your CI/CD pipeline or .env file
    kind: ClusterIssuer
  dnsNames:
    - longhorn.example.com
