apiVersion: v2
name: harbor-wrapper
description: A Helm wrapper for deploying Harbor registry
type: application
version: 0.1.0
appVersion: "1.16.2"

dependencies:
  - name: harbor
    version: 1.16.2
    repository: https://helm.goharbor.io
