ingressroute:
  enabled: true
  host: "mealie.example.com"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    secretName: "mealie-tls"

certificate:
  enabled: true
  name: mealie-tls
  secretName: mealie-tls
  issuer:
    name: "letsencrypt-staging"  # This value can be set via your CI/CD pipeline or .env file
    kind: ClusterIssuer
  dnsNames:
    - mealie.example.com

persistenceLonghorn:
  enabled: true
  restore: true             # Set this to true if you are restoring from backup
  pvcName: "mealie-pvc"
  pvName: "mealie-pv"       # Used for the static PV (restored volume)
  size: "10Gi"
  accessMode: "ReadWriteOnce"
  reclaimPolicy: "Retain"
  storageClassName: "longhorn"
  csiDriver: "driver.longhorn.io"
  numberOfReplicas: 2
  frontend: blockdev
  backupTargetName: default
  fromBackup: "s3://longhorn-backups@minio.example.com/longhorn?backup=dummy_backup_id&volume=mealie-pv"

#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#
strategy:
  type: Recreate

controllers:
  main:
    enabled: true
    containers:
      main:
        image:
          repository: ghcr.io/mealie-recipes/mealie
          tag: latest  # Ensure you're using the latest stable release
          pullPolicy: IfNotPresent
        env:
          TZ: America/New_York  # Set to Eastern Time
          BASE_URL: "https://mealie.example.com"
          DB_ENGINE: sqlite
          SQLITE_DB_FILE: "/app/data/mealie.db"
          ALLOW_SIGNUP: "false"  # Disable user signups
          TOKEN_TIME: "96"  # Token expiration time in hours
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
