replicaCount: 1

image:
  repository: triliumnext/notes
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingressroute:
  enabled: true
  host: "trilium.example.com"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    secretName: "trilium-tls"

certificate:
  enabled: true
  name: trilium-tls
  secretName: trilium-tls
  issuer:
    name: "letsencrypt-staging"
    kind: ClusterIssuer
  dnsNames:
    - trilium.example.com

persistence:
  enabled: false  # Disable the default PVC

persistenceLonghorn:
  enabled: true
  restore: true             # Set this to true if you are restoring from backup
  pvcName: "trilium-pvc"
  pvName: "trilium-pv"       # Used for the static PV (restored volume)
  size: "5Gi"
  accessMode: "ReadWriteOnce"
  reclaimPolicy: "Retain"
  storageClassName: "longhorn"
  csiDriver: "driver.longhorn.io"
  numberOfReplicas: 2
  frontend: blockdev
  backupTargetName: default
  fromBackup: "s3://longhorn-backups@minio.example.com/longhorn?backup=dummy_backup_id&volume=trilium-pv"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
