ingressroute:
  enabled: false
  host: "planka.example.company"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
  tls:
    secretName: "planka-tls"

certificate:
  enabled: false
  name: planka-tls
  secretName: planka-tls
  issuer:
    name: "letsencrypt-staging"
    kind: ClusterIssuer
  dnsNames:
    - planka.example.company

planka:
  # Default values for planka.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  replicaCount: 1

  image:
    repository: ghcr.io/plankanban/planka
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  # Generate a secret using openssl rand -base64 45
  secretkey: ""

  ## @param existingSecretkeySecret Name of an existing secret containing the session key string
  ## NOTE: Must contain key `key`
  ## NOTE: When it's set, the secretkey parameter is ignored
  existingSecretkeySecret: ""

  ## @param existingAdminCredsSecret Name of an existing secret containing the admin username and password
  ## NOTE: Must contain keys `username` and `password`
  ## NOTE: When it's set, the `admin_username` and `admin_password` parameters are ignored
  existingAdminCredsSecret: ""

  # Base url for PLANKA. Will override `ingress.hosts[0].host`
  # Defaults to `http://localhost:3000` if ingress is disabled.
  baseUrl: ""

  service:
    annotations: {}
    type: ClusterIP
    port: 1337
    ## @param service.containerPort PLANKA HTTP container port
    ## If empty will default to 1337
    ##
    containerPort: 1337

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  postgresql:
    enabled: true
    auth:
      database: planka
      username: planka
      password: ""
      postgresPassword: ""
      replicationPassword: ""
      # existingSecret: planka-postgresql
    serviceBindings:
      enabled: true

  ## Set this or existingDburlSecret if you disable the built-in postgresql deployment
  dburl:

  ## @param existingDburlSecret Name of an existing secret containing a DBurl connection string
  ## NOTE: Must contain key `uri`
  ## NOTE: When it's set, the `dburl` parameter is ignored
  ##
  existingDburlSecret: ""

  ## PVC-based data storage configuration
  persistence:
    enabled: false
    # existingClaim: netbox-data
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 10Gi

  ## OpenID Identity Management configuration
  ##
  ## Example:
  ## ---------------
  ## oidc:
  ##   enabled: true
  ##   clientId: sxxaAIAxVXlCxTmc1YLHBbQr8NL8MqLI2DUbt42d
  ##   clientSecret: om4RTMRVHRszU7bqxB7RZNkHIzA8e4sGYWxeCwIMYQXPwEBWe4SY5a0wwCe9ltB3zrq5f0dnFnp34cEHD7QSMHsKvV9AiV5Z7eqDraMnv0I8IFivmuV5wovAECAYreSI
  ##   issuerUrl: https://auth.local/application/o/planka/
  ##   admin:
  ##     roles:
  ##       - planka-admin
  ##
  ## ---------------
  ## NOTE: A minimal configuration requires setting `clientId`, `clientSecret` and `issuerUrl`. (plus `admin.roles` for administrators)
  ## ref: https://docs.planka.cloud/docs/configuration/oidc/
  ##
