---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: cert-manager
spec:
  encryptedData:
    apiKey: randomencrypteddata
    email: randomencrypteddata
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: cert-manager
