---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-actions-token
  namespace: gitea
spec:
  encryptedData:
    token: randomencrypteddata
  template:
    metadata:
      creationTimestamp: null
      name: gitea-actions-token
      namespace: gitea
    type: Opaque
