---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: longhorn-auth
  namespace: longhorn-system
spec:
  encryptedData:
    users: AgAlV7Lh2rlcVBYxca6rJWv5JfJqAN4LbNb8b/k1Vu0rBb94sfnw7wNx/YTcFZ9tVIOOJllSrzeHI3gQPiCpiCUIdG1IrmrLOKWolRYdlXK+MOx+LeJU35Mglu57UcJtbjq+5+pKFiqX60A3IEJ5k+hCV7QlTZvkV3ygnrPcBmc4p+WMpsHtkmsIjHNDKXUi6yZKYqWP70FhtveCuc3GRxenNRx7m4bSxv6MFks1OlVT3wnJXgO8ixA2vo//wewi+xL9Xuva2gFWeYqRDmgyI9oSX7ePnadZkkboSvRzvlTpF+oMkrzjXP+G7B4JirDcyK1RhEK2wUS0O46RXCpz41EqT+/rMxtXc/VQi0bPV6eGdW4Plkvb5fLeJVpfsH8JgHW60mywRCmPpGyBt8KM7Qca87nGuKPoJQDtWzBZMRC0pmXadfuUmvSZ9B0hkVv3g5dV9lBMKc5ClhcXeXDr49Vh8/fh9glQNEYkJIsjQqk29slgqw3uwRhPK9AQ6QJFEm8Zzn8yYeNeyATbLEtLKQICSdLdAMq8SWr3JU2YrArwdkEYQtIf37Vz6YoidrkzkcBFS6irfK6LgMRNbUEhIohMIADpc8TfqsgdNzxzABbhL0XIlteQ9iFZwsx92x4UOAmVwBAgN3o3pANNs8bueFS9apk9zmOooIM8mTtJzvVB2bMj2OkUQIZTXFTMRof39i/Hu9HvGznbq01nQUFYo1Y8imyTWC559HFDZdjiAkoDqfTIj6FK/X5WsfKjaMic
  template:
    metadata:
      creationTimestamp: null
      name: longhorn-auth
      namespace: longhorn-system
    type: Opaque
